// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-GzaRWNcbaT5Ok4S3j6c9dQEbqSX-RUQ',
    appId: '1:995410380657:web:0cf1198224190e3b51d8d0',
    messagingSenderId: '995410380657',
    projectId: 'event-fyp',
    authDomain: 'event-fyp.firebaseapp.com',
    storageBucket: 'event-fyp.firebasestorage.app',
    measurementId: 'G-S4XQXWC0QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpOVE3KWqXrL3N51o4xpGZkhXDBF281U8',
    appId: '1:995410380657:android:5d0de5ef050c3e8351d8d0',
    messagingSenderId: '995410380657',
    projectId: 'event-fyp',
    storageBucket: 'event-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7n6nn7hTj_f4heT0f3IJrXE9XNNOaJp0',
    appId: '1:995410380657:ios:eac9d092a0f5f4ba51d8d0',
    messagingSenderId: '995410380657',
    projectId: 'event-fyp',
    storageBucket: 'event-fyp.firebasestorage.app',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7n6nn7hTj_f4heT0f3IJrXE9XNNOaJp0',
    appId: '1:995410380657:ios:eac9d092a0f5f4ba51d8d0',
    messagingSenderId: '995410380657',
    projectId: 'event-fyp',
    storageBucket: 'event-fyp.firebasestorage.app',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-GzaRWNcbaT5Ok4S3j6c9dQEbqSX-RUQ',
    appId: '1:995410380657:web:21460971844dee3d51d8d0',
    messagingSenderId: '995410380657',
    projectId: 'event-fyp',
    authDomain: 'event-fyp.firebaseapp.com',
    storageBucket: 'event-fyp.firebasestorage.app',
    measurementId: 'G-96REWETCB7',
  );
}
