import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:csv/csv.dart';
import 'package:provider/provider.dart';
import '../models/venue_model.dart';
import '../services/firestore_service.dart';
import '../services/auth_service.dart';
import 'edit_venue_screen.dart';
import 'manage_bookings_screen.dart';

class AdminScreen extends StatefulWidget {
  const AdminScreen({super.key});

  @override
  State<AdminScreen> createState() => AdminScreenState();
}

class AdminScreenState extends State<AdminScreen>
    with SingleTickerProviderStateMixin {
  final _formKey = GlobalKey<FormState>();
  final _firestoreService = FirestoreService();
  String _name = '';
  String _description = '';
  String _imageUrl = '';
  String _category = 'Resort';
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 4, vsync: this);
  }

  void _addVenue() {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      final newVenue = Venue(
        id: '', // ID will be generated by Firestore
        name: _name,
        description: _description,
        imageUrl: _imageUrl,
        category: _category,
      );
      _firestoreService.addVenue(newVenue).then((_) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Venue added successfully!')),
        );
        _formKey.currentState!.reset();
      });
    }
  }

  Future<void> _importFromJson() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['json'],
    );
    if (result == null) return;

    final file = result.files.first;
    final contents = utf8.decode(file.bytes!);
    final List<dynamic> jsonList = json.decode(contents);

    final venues = jsonList
        .map(
          (json) => Venue(
            id: '',
            name: json['name'] ?? '',
            description: json['description'] ?? '',
            imageUrl: json['imageUrl'] ?? '',
            category: json['category'] ?? '',
          ),
        )
        .toList();

    await _firestoreService.addVenues(venues);
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Venues imported successfully!')),
    );
  }

  Future<void> _importFromCsv() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['csv'],
    );
    if (result == null) return;

    final file = result.files.first;
    final contents = utf8.decode(file.bytes!);
    final List<List<dynamic>> csvTable = const CsvToListConverter().convert(
      contents,
    );

    final venues = csvTable
        .skip(1)
        .map(
          (row) => Venue(
            id: '',
            name: row[0].toString(),
            description: row[1].toString(),
            imageUrl: row[2].toString(),
            category: row[3].toString(),
          ),
        )
        .toList();

    await _firestoreService.addVenues(venues);
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Venues imported successfully!')),
    );
  }

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context, listen: false);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Admin Panel'),
        bottom: TabBar(
          controller: _tabController,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white70,
          indicatorColor: Colors.white,
          tabs: const [
            Tab(icon: Icon(Icons.add), text: 'Add Venue'),
            Tab(icon: Icon(Icons.import_export), text: 'Import Venues'),
            Tab(icon: Icon(Icons.edit), text: 'Manage Venues'),
            Tab(icon: Icon(Icons.book_online), text: 'Manage Bookings'),
          ],
        ),
      ),
      drawer: Drawer(
        child: ListView(
          padding: EdgeInsets.zero,
          children: [
            DrawerHeader(
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary,
              ),
              child: const Text(
                'Admin Menu',
                style: TextStyle(color: Colors.white, fontSize: 24),
              ),
            ),
            ListTile(
              leading: const Icon(Icons.home),
              title: const Text('Home'),
              onTap: () {
                Navigator.of(context).pushReplacementNamed('/home');
              },
            ),
            ListTile(
              leading: const Icon(Icons.logout),
              title: const Text('Logout'),
              onTap: () {
                authService.signOut();
                Navigator.of(context).pushReplacementNamed('/auth');
              },
            ),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // Add Venue Tab
          SingleChildScrollView(
            padding: const EdgeInsets.all(16.0),
            child: Card(
              elevation: 4,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      TextFormField(
                        decoration: const InputDecoration(labelText: 'Name'),
                        validator: (value) =>
                            value!.isEmpty ? 'Please enter a name' : null,
                        onSaved: (value) => _name = value!,
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Description',
                        ),
                        validator: (value) => value!.isEmpty
                            ? 'Please enter a description'
                            : null,
                        onSaved: (value) => _description = value!,
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        decoration: const InputDecoration(
                          labelText: 'Image URL',
                        ),
                        validator: (value) =>
                            value!.isEmpty ? 'Please enter an image URL' : null,
                        onSaved: (value) => _imageUrl = value!,
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        decoration: const InputDecoration(
                          labelText: 'Category',
                        ),
                        initialValue: _category,
                        items:
                            ['Resort', 'Corporate Hall', 'Banquet', 'Marquee']
                                .map(
                                  (label) => DropdownMenuItem(
                                    value: label,
                                    child: Text(label),
                                  ),
                                )
                                .toList(),
                        onChanged: (value) =>
                            setState(() => _category = value!),
                      ),
                      const SizedBox(height: 24),
                      ElevatedButton(
                        onPressed: _addVenue,
                        child: const Text('Add Venue'),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),

          // Import Venues Tab
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton.icon(
                  onPressed: _importFromJson,
                  icon: const Icon(Icons.code),
                  label: const Text('Import from JSON'),
                  style: ElevatedButton.styleFrom(
                    minimumSize: const Size(double.infinity, 50),
                  ),
                ),
                const SizedBox(height: 20),
                ElevatedButton.icon(
                  onPressed: _importFromCsv,
                  icon: const Icon(Icons.table_chart),
                  label: const Text('Import from CSV'),
                  style: ElevatedButton.styleFrom(
                    minimumSize: const Size(double.infinity, 50),
                  ),
                ),
              ],
            ),
          ),

          // Manage Venues Tab
          StreamBuilder<List<Venue>>(
            stream: _firestoreService.getVenues(),
            builder: (context, snapshot) {
              if (snapshot.hasError) {
                return const Center(child: Text('Error loading venues.'));
              }
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }
              final venues = snapshot.data ?? [];
              return ListView.builder(
                itemCount: venues.length,
                itemBuilder: (context, index) {
                  final venue = venues[index];
                  return ListTile(
                    leading: CircleAvatar(
                      backgroundImage: NetworkImage(venue.imageUrl),
                    ),
                    title: Text(venue.name),
                    subtitle: Text(venue.category),
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        IconButton(
                          icon: const Icon(Icons.edit),
                          onPressed: () {
                            Navigator.of(context).push(
                              MaterialPageRoute(
                                builder: (context) => EditVenueScreen(venue: venue),
                              ),
                            );
                          },
                        ),
                        IconButton(
                          icon: const Icon(Icons.delete),
                          onPressed: () {
                            _firestoreService.deleteVenue(venue.id);
                          },
                        ),
                      ],
                    ),
                  );
                },
              );
            },
          ),
          const ManageBookingsScreen(),
        ],
      ),
    );
  }
}
